const API=(window.TWOCHAT_API||'').replace(/\/$/,'');
let room='',name='',ws=null,pc=null,localStream=null,pendingOffer=null,isCaller=false;
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function addMessage(m){const d=document.createElement('div');d.className='msg '+(m.sender===name?'mine':'');d.innerHTML=esc(m.text).replace(/\n/g,'<br>')+'<small>'+esc(m.sender)+' · '+new Date(m.created_at||Date.now()).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})+'</small>'; $('messages').appendChild(d);$('messages').scrollTop=$('messages').scrollHeight}
async function loadMessages(){const r=await fetch(`${API}/api/messages?room=${encodeURIComponent(room)}`);if(!r.ok)throw Error('Messages unavailable');const a=await r.json();$('messages').innerHTML='';a.forEach(addMessage)}
async function sendMessage(text){const r=await fetch(`${API}/api/messages`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({room,name,text})});if(!r.ok)throw Error('Send failed')}
function connect(){const u=new URL(API);u.protocol=u.protocol==='https:'?'wss:':'ws:';u.pathname='/ws';u.search=new URLSearchParams({room,name});ws=new WebSocket(u);ws.onopen=()=>{$('status').textContent='Online';$('status').style.color='#55d98b'};ws.onclose=()=>{$('status').textContent='Reconnecting…';setTimeout(connect,2500)};ws.onmessage=async e=>{const x=JSON.parse(e.data);if(x.type==='message')addMessage(x);if(x.type==='peer')$('status').textContent=x.online?'Both online':'Waiting for the other person';if(x.type==='offer'){pendingOffer=x;showIncoming(x.video)}if(x.type==='answer'&&pc)await pc.setRemoteDescription(x.answer);if(x.type==='candidate'&&pc)try{await pc.addIceCandidate(x.candidate)}catch{}if(x.type==='hangup')closeCall(false)}}
function signal(x){if(ws&&ws.readyState===1)ws.send(JSON.stringify(x))}
async function makePC(video,caller){pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});pc.onicecandidate=e=>e.candidate&&signal({type:'candidate',candidate:e.candidate});pc.ontrack=e=>{$('remoteVideo').srcObject=e.streams[0]};pc.onconnectionstatechange=()=>{if(['failed','disconnected','closed'].includes(pc.connectionState))closeCall(false)};localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:video});$('localVideo').srcObject=localStream;localStream.getTracks().forEach(t=>pc.addTrack(t,localStream));$('call').classList.remove('hidden');$('incoming').classList.add('hidden');if(caller){const offer=await pc.createOffer();await pc.setLocalDescription(offer);signal({type:'offer',offer:pc.localDescription,video})}}
function showIncoming(video){$('call').classList.remove('hidden');$('incoming').classList.remove('hidden');$('callTitle').textContent='Incoming '+(video?'video':'voice')+' call';$('incomingText').textContent=`${pendingOffer.from} is calling`}
async function acceptCall(){const o=pendingOffer;pendingOffer=null;await makePC(o.video,false);await pc.setRemoteDescription(o.offer);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);signal({type:'answer',answer:pc.localDescription})}
function closeCall(send=true){if(send)signal({type:'hangup'});if(localStream){localStream.getTracks().forEach(t=>t.stop());localStream=null}if(pc){pc.close();pc=null}$('remoteVideo').srcObject=null;$('localVideo').srcObject=null;$('call').classList.add('hidden');$('incoming').classList.add('hidden');pendingOffer=null}
$('joinBtn').onclick=async()=>{name=$('name').value.trim();room=$('room').value.trim();if(!name||!room)return alert('Enter your name and a private room code.');if(!API||API.includes('REPLACE-WITH'))return alert('Set the Cloudflare Worker URL in chat/config.js first.');$('join').classList.add('hidden');$('chat').classList.remove('hidden');$('roomTitle').textContent='Room: '+room;try{await loadMessages();connect()}catch(e){alert(e.message);$('join').classList.remove('hidden');$('chat').classList.add('hidden')}};
$('composer').onsubmit=async e=>{e.preventDefault();const t=$('message').value.trim();if(!t)return;try{await sendMessage(t);$('message').value=''}catch(e){alert(e.message)}};
$('voiceBtn').onclick=()=>makePC(false,true);$('videoBtn').onclick=()=>makePC(true,true);$('hangup').onclick=()=>closeCall(true);$('accept').onclick=acceptCall;$('decline').onclick=()=>closeCall(true);$('mute').onclick=()=>{const t=localStream?.getAudioTracks()[0];if(t){t.enabled=!t.enabled;$('mute').textContent=t.enabled?'Mute':'Unmute'}};$('camera').onclick=()=>{const t=localStream?.getVideoTracks()[0];if(t){t.enabled=!t.enabled;$('camera').textContent=t.enabled?'Camera':'Camera off'}};
