name = "twochat"
main = "src/worker.js"
compatibility_date = "2026-08-28"

[[d1_databases]]
binding = "DB"
database_name = "twochat"
database_id = "582f897d-f892-4fc6-8cee-ff7d8bdbc1b8"
migrations_dir = "migrations"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "Room"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]

[triggers]
crons = ["0 0 * * *"]
